### ISSUE TITLE
Can't find the data to run main_test_avatarposer.py

### ISSUE THREAD

**Issue by TimofeyKruk** [eth-siplab/AvatarPoser#16]
Thank you for your work!

When running main_test_avatarposer.py the following error occurs:
```
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/AvatarPoser/data/dataset_amass.py", line 66, in __getitem__
    rotation_local_full_gt_list = data['rotation_local_full_gt_list']
  File "/usr/local/lib/python3.8/dist-packages/numpy/lib/npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'rotation_local_full_gt_list is not a file in the archive'
```
**KeyError: 'rotation_local_full_gt_list is not a file in the archive'.**. 

Downloaded BMLrub and HDM05 datasets and placed some of the files into AvatarPoser/data_cameraready_fps60/dataset1/test. And when I tried to load this .npz files separately they seem to have different keys. 
There were ['trans', 'gender', 'mocap_framerate', 'betas', 'dmpls', 'poses'] keys, but no **'rotation_local_full_gt_list'**.

Can you help me, please, to find the right data to test?

**Comment by jiaxi-jiang** [comment]
Hi, thanks for your interest in our work! You should firstly run prepare_data.py to preprocess the original data.
